// Pronunciations for every word 👂 Hear it, find it can SPEAK, so a test can
// prove no listening board offers two words that sound alike.
//
// Why a dictionary: Word Cards keeps sound-alike words off one board with a
// HOMOPHONES list, and typed by hand that list missed fairy/ferry, which an
// American voice says identically. The game says the word and he taps it, so
// both would have been right answers. tests/site.test.js now requires the
// list to hold every pair this dictionary says sound alike.
//
// Adding a card: look the word up in the CMU Pronouncing Dictionary
// (http://www.speech.cs.cmu.edu/cgi-bin/cmudict) and copy its line(s) here
// UNCHANGED, stress marks and all. The listening test fails until you do,
// on purpose: a word nobody has checked is a word that might be a homophone.
//
// Source: the CMU Pronouncing Dictionary, entries copied unchanged for the
// words the listening game can speak (one entry may hold several readings).
// It is not loaded by the site; it is test data. Its licence, kept here as the
// licence requires:
//
// Copyright (C) 1993-2015 Carnegie Mellon University. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//    The contents of this file are deemed to be source code.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in
//    the documentation and/or other materials provided with the
//    distribution.
//
// This work was supported in part by funding from the Defense Advanced
// Research Projects Agency, the Office of Naval Research and the National
// Science Foundation of the United States of America, and by member
// companies of the Carnegie Mellon Sphinx Speech Consortium. We acknowledge
// the contributions of many volunteers to the expansion and improvement of
// this dictionary.
//
// THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND
// ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
// NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

module.exports = {
  "alien": ["EY1 L IY0 AH0 N"],
  "all": ["AO1 L"],
  "am": ["AE1 M", "EY1 EH1 M"],
  "ambulance": ["AE1 M B Y AH0 L AH0 N S"],
  "an": ["AE1 N", "AH0 N"],
  "anchor": ["AE1 NG K ER0"],
  "and": ["AH0 N D", "AE1 N D"],
  "ant": ["AE1 N T"],
  "ape": ["EY1 P"],
  "apple": ["AE1 P AH0 L"],
  "are": ["AA1 R", "ER0"],
  "artist": ["AA1 R T AH0 S T", "AA1 R T IH0 S T"],
  "as": ["AE1 Z", "EH1 Z"],
  "astronaut": ["AE1 S T R AH0 N AA2 T"],
  "at": ["AE1 T"],
  "avocado": ["AE2 V AH0 K AA1 D OW0"],
  "axe": ["AE1 K S"],
  "baby": ["B EY1 B IY0"],
  "backpack": ["B AE1 K P AE2 K"],
  "bacon": ["B EY1 K AH0 N"],
  "badger": ["B AE1 JH ER0"],
  "bag": ["B AE1 G"],
  "bagel": ["B EY1 G AH0 L"],
  "ball": ["B AO1 L"],
  "balloon": ["B AH0 L UW1 N"],
  "banana": ["B AH0 N AE1 N AH0"],
  "bandage": ["B AE1 N D IH0 JH"],
  "basket": ["B AE1 S K AH0 T"],
  "basketball": ["B AE1 S K AH0 T B AO2 L"],
  "bat": ["B AE1 T"],
  "battery": ["B AE1 T ER0 IY0"],
  "be": ["B IY1", "B IY0"],
  "beach": ["B IY1 CH"],
  "bear": ["B EH1 R"],
  "beard": ["B IH1 R D"],
  "beaver": ["B IY1 V ER0"],
  "bed": ["B EH1 D"],
  "bee": ["B IY1"],
  "beetle": ["B IY1 T AH0 L"],
  "bell": ["B EH1 L"],
  "berry": ["B EH1 R IY0"],
  "bike": ["B AY1 K"],
  "bird": ["B ER1 D"],
  "bison": ["B AY1 S AH0 N"],
  "black": ["B L AE1 K"],
  "blue": ["B L UW1"],
  "boat": ["B OW1 T"],
  "bolt": ["B OW1 L T"],
  "bone": ["B OW1 N"],
  "book": ["B UH1 K"],
  "boot": ["B UW1 T"],
  "bowl": ["B OW1 L"],
  "bowling": ["B OW1 L IH0 NG"],
  "box": ["B AA1 K S"],
  "boy": ["B OY1"],
  "brain": ["B R EY1 N"],
  "bread": ["B R EH1 D"],
  "broccoli": ["B R AA1 K AH0 L IY0", "B R AA1 K L IY0"],
  "broom": ["B R UW1 M"],
  "brown": ["B R AW1 N"],
  "bubble": ["B AH1 B AH0 L"],
  "bucket": ["B AH1 K AH0 T", "B AH1 K IH0 T"],
  "bug": ["B AH1 G"],
  "builder": ["B IH1 L D ER0"],
  "bull": ["B UH1 L"],
  "burger": ["B ER1 G ER0"],
  "burrito": ["B ER0 IY1 T OW0"],
  "bus": ["B AH1 S"],
  "but": ["B AH1 T"],
  "butter": ["B AH1 T ER0"],
  "butterfly": ["B AH1 T ER0 F L AY2"],
  "by": ["B AY1"],
  "cactus": ["K AE1 K T AH0 S"],
  "cake": ["K EY1 K"],
  "camel": ["K AE1 M AH0 L"],
  "camera": ["K AE1 M ER0 AH0", "K AE1 M R AH0"],
  "can": ["K AE1 N", "K AH0 N"],
  "candle": ["K AE1 N D AH0 L"],
  "candy": ["K AE1 N D IY0"],
  "canoe": ["K AH0 N UW1"],
  "cap": ["K AE1 P"],
  "car": ["K AA1 R"],
  "carrot": ["K AE1 R AH0 T", "K EH1 R AH0 T"],
  "cart": ["K AA1 R T"],
  "castle": ["K AE1 S AH0 L"],
  "cat": ["K AE1 T"],
  "chain": ["CH EY1 N"],
  "chair": ["CH EH1 R"],
  "cheese": ["CH IY1 Z"],
  "cherry": ["CH EH1 R IY0"],
  "chick": ["CH IH1 K"],
  "chocolate": ["CH AO1 K L AH0 T"],
  "clap": ["K L AE1 P"],
  "climb": ["K L AY1 M"],
  "clock": ["K L AA1 K"],
  "cloud": ["K L AW1 D"],
  "clover": ["K L OW1 V ER0"],
  "coat": ["K OW1 T"],
  "coconut": ["K OW1 K AH0 N AH2 T"],
  "coin": ["K OY1 N"],
  "cold": ["K OW1 L D"],
  "comet": ["K AA1 M AH0 T"],
  "compass": ["K AH1 M P AH0 S"],
  "cook": ["K UH1 K"],
  "cookie": ["K UH1 K IY0"],
  "cool": ["K UW1 L"],
  "corn": ["K AO1 R N"],
  "cow": ["K AW1"],
  "crab": ["K R AE1 B"],
  "crayon": ["K R EY1 AA2 N"],
  "cricket": ["K R IH1 K AH0 T", "K R IH1 K IH0 T"],
  "crocodile": ["K R AA1 K AH0 D AY2 L"],
  "crown": ["K R AW1 N"],
  "cry": ["K R AY1"],
  "cucumber": ["K Y UW1 K AH0 M B ER0"],
  "cup": ["K AH1 P"],
  "cupcake": ["K AH1 P K EY2 K"],
  "dad": ["D AE1 D"],
  "dance": ["D AE1 N S"],
  "dark": ["D AA1 R K"],
  "darts": ["D AA1 R T S"],
  "deer": ["D IH1 R"],
  "desert": ["D EH1 Z ER0 T", "D IH0 Z ER1 T"],
  "dice": ["D AY1 S"],
  "dinosaur": ["D AY1 N AH0 S AO2 R"],
  "do": ["D UW1"],
  "doctor": ["D AA1 K T ER0", "D AO1 K T ER0"],
  "dog": ["D AO1 G"],
  "doll": ["D AA1 L"],
  "dolphin": ["D AA1 L F AH0 N"],
  "donut": ["D OW1 N AH2 T"],
  "door": ["D AO1 R"],
  "dove": ["D AH1 V", "D OW1 V"],
  "dragon": ["D R AE1 G AH0 N"],
  "dress": ["D R EH1 S"],
  "drum": ["D R AH1 M"],
  "duck": ["D AH1 K"],
  "eagle": ["IY1 G AH0 L"],
  "ear": ["IY1 R", "IH1 R"],
  "earth": ["ER1 TH"],
  "egg": ["EH1 G"],
  "eight": ["EY1 T"],
  "elephant": ["EH1 L AH0 F AH0 N T"],
  "elf": ["EH1 L F"],
  "envelope": ["EH1 N V AH0 L OW2 P"],
  "eye": ["AY1"],
  "eyes": ["AY1 Z"],
  "face": ["F EY1 S"],
  "fairy": ["F EH1 R IY0"],
  "family": ["F AE1 M AH0 L IY0", "F AE1 M L IY0"],
  "farmer": ["F AA1 R M ER0"],
  "fast": ["F AE1 S T"],
  "feather": ["F EH1 DH ER0"],
  "feet": ["F IY1 T"],
  "ferry": ["F EH1 R IY0"],
  "find": ["F AY1 N D"],
  "finger": ["F IH1 NG G ER0"],
  "fire": ["F AY1 ER0", "F AY1 R"],
  "firefighter": ["F AY1 R F AY2 T ER0"],
  "first": ["F ER1 S T"],
  "fish": ["F IH1 SH"],
  "five": ["F AY1 V"],
  "flag": ["F L AE1 G"],
  "flamingo": ["F L AH0 M IH1 NG G OW0"],
  "flower": ["F L AW1 ER0"],
  "foot": ["F UH1 T"],
  "for": ["F AO1 R", "F ER0", "F R ER0"],
  "fork": ["F AO1 R K"],
  "four": ["F AO1 R"],
  "fox": ["F AA1 K S"],
  "fries": ["F R AY1 Z"],
  "frog": ["F R AA1 G"],
  "fun": ["F AH1 N"],
  "funny": ["F AH1 N IY0"],
  "game": ["G EY1 M"],
  "garlic": ["G AA1 R L IH0 K"],
  "gem": ["JH EH1 M"],
  "ghost": ["G OW1 S T"],
  "gift": ["G IH1 F T"],
  "giraffe": ["JH ER0 AE1 F"],
  "girl": ["G ER1 L"],
  "glasses": ["G L AE1 S AH0 Z", "G L AE1 S IH0 Z"],
  "glove": ["G L AH1 V"],
  "go": ["G OW1"],
  "goat": ["G OW1 T"],
  "good": ["G UH1 D", "G IH0 D"],
  "grandma": ["G R AE1 N D M AA0"],
  "grandpa": ["G R AE1 N D P AA2"],
  "grape": ["G R EY1 P"],
  "grass": ["G R AE1 S"],
  "green": ["G R IY1 N"],
  "guitar": ["G IH0 T AA1 R"],
  "had": ["HH AE1 D"],
  "ham": ["HH AE1 M"],
  "hammer": ["HH AE1 M ER0"],
  "hamster": ["HH AE1 M S T ER0"],
  "hand": ["HH AE1 N D"],
  "happy": ["HH AE1 P IY0"],
  "hare": ["HH EH1 R"],
  "has": ["HH AE1 Z", "HH AH0 Z"],
  "hat": ["HH AE1 T"],
  "he": ["HH IY1"],
  "heart": ["HH AA1 R T"],
  "hedgehog": ["HH EH1 JH HH AA2 G"],
  "helicopter": ["HH EH1 L IH0 K AA2 P T ER0"],
  "help": ["HH EH1 L P"],
  "hen": ["HH EH1 N"],
  "her": ["HH ER1", "HH ER0"],
  "him": ["HH IH1 M", "IH0 M"],
  "his": ["HH IH1 Z", "HH IH0 Z"],
  "hold": ["HH OW1 L D"],
  "hole": ["HH OW1 L"],
  "honey": ["HH AH1 N IY0"],
  "hook": ["HH UH1 K"],
  "horse": ["HH AO1 R S"],
  "hot": ["HH AA1 T"],
  "house": ["HH AW1 S"],
  "hug": ["HH AH1 G"],
  "hut": ["HH AH1 T"],
  "ice": ["AY1 S"],
  "if": ["IH1 F", "IH0 F"],
  "in": ["IH0 N", "IH1 N"],
  "is": ["IH1 Z", "IH0 Z"],
  "island": ["AY1 L AH0 N D"],
  "it": ["IH1 T", "IH0 T"],
  "jet": ["JH EH1 T"],
  "juggle": ["JH AH1 G AH0 L"],
  "juice": ["JH UW1 S"],
  "jump": ["JH AH1 M P"],
  "kangaroo": ["K AE2 NG G ER0 UW1"],
  "key": ["K IY1"],
  "kid": ["K IH1 D"],
  "kind": ["K AY1 N D"],
  "kiss": ["K IH1 S"],
  "kite": ["K AY1 T"],
  "kiwi": ["K IY1 W IY0"],
  "knife": ["N AY1 F"],
  "knot": ["N AA1 T"],
  "koala": ["K OW0 AA1 L AH0"],
  "ladder": ["L AE1 D ER0"],
  "ladybug": ["L EY1 D IY0 B AH2 G"],
  "laptop": ["L AE1 P T AA2 P"],
  "laugh": ["L AE1 F"],
  "leaf": ["L IY1 F"],
  "leg": ["L EH1 G"],
  "lemon": ["L EH1 M AH0 N"],
  "lettuce": ["L EH1 T AH0 S"],
  "lift": ["L IH1 F T"],
  "light": ["L AY1 T"],
  "lightning": ["L AY1 T N IH0 NG"],
  "lion": ["L AY1 AH0 N"],
  "lizard": ["L IH1 Z ER0 D"],
  "llama": ["L AA1 M AH0"],
  "lobster": ["L AA1 B S T ER0"],
  "lock": ["L AA1 K"],
  "log": ["L AO1 G"],
  "lollipop": ["L AA1 L IY0 P AA2 P"],
  "loud": ["L AW1 D"],
  "lungs": ["L AH1 NG Z"],
  "mad": ["M AE1 D"],
  "magnet": ["M AE1 G N AH0 T"],
  "mailbox": ["M EY1 L B AA2 K S"],
  "mango": ["M AE1 NG G OW0"],
  "map": ["M AE1 P"],
  "maple": ["M EY1 P AH0 L"],
  "me": ["M IY1"],
  "meat": ["M IY1 T"],
  "medal": ["M EH1 D AH0 L"],
  "melon": ["M EH1 L AH0 N"],
  "mermaid": ["M ER1 M EY2 D"],
  "milk": ["M IH1 L K"],
  "mirror": ["M IH1 R ER0"],
  "mom": ["M AA1 M"],
  "money": ["M AH1 N IY0"],
  "monkey": ["M AH1 NG K IY0"],
  "moon": ["M UW1 N"],
  "mosquito": ["M AH0 S K IY1 T OW0"],
  "motorbike": ["M OW1 T ER0 B AY2 K"],
  "mountain": ["M AW1 N T AH0 N"],
  "mouse": ["M AW1 S"],
  "mouth": ["M AW1 TH"],
  "mug": ["M AH1 G"],
  "mushroom": ["M AH1 SH R UW0 M"],
  "my": ["M AY1"],
  "nine": ["N AY1 N"],
  "ninja": ["N IH1 N JH AH0"],
  "no": ["N OW1"],
  "noodle": ["N UW1 D AH0 L"],
  "nose": ["N OW1 Z"],
  "not": ["N AA1 T"],
  "nut": ["N AH1 T"],
  "octopus": ["AA1 K T AH0 P UH2 S"],
  "of": ["AH1 V"],
  "olive": ["AA1 L AH0 V", "AA1 L IH0 V"],
  "on": ["AA1 N", "AO1 N"],
  "one": ["W AH1 N"],
  "onion": ["AH1 N Y AH0 N"],
  "or": ["AO1 R", "ER0"],
  "orange": ["AO1 R AH0 N JH", "AO1 R IH0 N JH"],
  "otter": ["AA1 T ER0"],
  "owl": ["AW1 L"],
  "paint": ["P EY1 N T"],
  "pan": ["P AE1 N"],
  "pancake": ["P AE1 N K EY2 K"],
  "panda": ["P AE1 N D AH0"],
  "pants": ["P AE1 N T S"],
  "paper": ["P EY1 P ER0"],
  "parachute": ["P EH1 R AH0 SH UW2 T"],
  "parrot": ["P EH1 R AH0 T"],
  "pasta": ["P AA1 S T AH0"],
  "peach": ["P IY1 CH"],
  "peacock": ["P IY1 K AA2 K"],
  "pear": ["P EH1 R"],
  "pen": ["P EH1 N"],
  "pencil": ["P EH1 N S AH0 L"],
  "penguin": ["P EH1 NG G W AH0 N"],
  "people": ["P IY1 P AH0 L"],
  "pepper": ["P EH1 P ER0"],
  "phone": ["F OW1 N"],
  "piano": ["P IY0 AE1 N OW0", "P IY0 AE1 N AH0"],
  "pie": ["P AY1"],
  "pig": ["P IH1 G"],
  "pilot": ["P AY1 L AH0 T"],
  "pin": ["P IH1 N"],
  "pineapple": ["P AY1 N AE2 P AH0 L"],
  "pink": ["P IH1 NG K"],
  "pizza": ["P IY1 T S AH0"],
  "planet": ["P L AE1 N AH0 T"],
  "plant": ["P L AE1 N T"],
  "plate": ["P L EY1 T"],
  "point": ["P OY1 N T"],
  "police": ["P AH0 L IY1 S"],
  "popcorn": ["P AA1 P K AO2 R N"],
  "potato": ["P AH0 T EY1 T OW2"],
  "pretzel": ["P R EH1 T Z AH0 L"],
  "prince": ["P R IH1 N S"],
  "pudding": ["P UH1 D IH0 NG"],
  "pup": ["P AH1 P"],
  "purple": ["P ER1 P AH0 L"],
  "puzzle": ["P AH1 Z AH0 L"],
  "quiet": ["K W AY1 AH0 T"],
  "rabbit": ["R AE1 B AH0 T", "R AE1 B IH0 T"],
  "radio": ["R EY1 D IY0 OW2"],
  "rain": ["R EY1 N"],
  "rainbow": ["R EY1 N B OW2"],
  "ram": ["R AE1 M"],
  "rat": ["R AE1 T"],
  "read": ["R EH1 D", "R IY1 D"],
  "red": ["R EH1 D"],
  "rice": ["R AY1 S"],
  "ride": ["R AY1 D"],
  "ring": ["R IH1 NG"],
  "river": ["R IH1 V ER0"],
  "robot": ["R OW1 B AA2 T", "R OW1 B AH2 T"],
  "rock": ["R AA1 K"],
  "rocket": ["R AA1 K AH0 T"],
  "rooster": ["R UW1 S T ER0"],
  "rose": ["R OW1 Z"],
  "ruler": ["R UW1 L ER0"],
  "run": ["R AH1 N"],
  "sad": ["S AE1 D"],
  "salad": ["S AE1 L AH0 D"],
  "salt": ["S AO1 L T"],
  "sandals": ["S AE1 N D AH0 L Z"],
  "sandwich": ["S AE1 N D W IH0 CH", "S AE1 N W IH0 CH", "S AE1 M W IH0 CH"],
  "saw": ["S AO1"],
  "scared": ["S K EH1 R D"],
  "scarf": ["S K AA1 R F"],
  "scissors": ["S IH1 Z ER0 Z"],
  "scooter": ["S K UW1 T ER0"],
  "seal": ["S IY1 L"],
  "second": ["S EH1 K AH0 N D"],
  "seed": ["S IY1 D"],
  "seven": ["S EH1 V AH0 N"],
  "shark": ["SH AA1 R K"],
  "she": ["SH IY1"],
  "sheep": ["SH IY1 P"],
  "shell": ["SH EH1 L"],
  "ship": ["SH IH1 P"],
  "shirt": ["SH ER1 T"],
  "shoe": ["SH UW1"],
  "shorts": ["SH AO1 R T S"],
  "shower": ["SH AW1 ER0"],
  "shrimp": ["SH R IH1 M P"],
  "sick": ["S IH1 K"],
  "silly": ["S IH1 L IY0"],
  "sing": ["S IH1 NG"],
  "singer": ["S IH1 NG ER0"],
  "sink": ["S IH1 NG K"],
  "siren": ["S AY1 R AH0 N"],
  "six": ["S IH1 K S"],
  "skate": ["S K EY1 T"],
  "skateboard": ["S K EY1 T B AO2 R D"],
  "ski": ["S K IY1"],
  "skunk": ["S K AH1 NG K"],
  "sled": ["S L EH1 D"],
  "sleep": ["S L IY1 P"],
  "sleepy": ["S L IY1 P IY0"],
  "sloth": ["S L OW1 TH"],
  "smile": ["S M AY1 L"],
  "snail": ["S N EY1 L"],
  "snake": ["S N EY1 K"],
  "snow": ["S N OW1"],
  "snowman": ["S N OW1 M AE2 N"],
  "so": ["S OW1"],
  "soap": ["S OW1 P"],
  "sock": ["S AA1 K"],
  "sofa": ["S OW1 F AH0"],
  "soup": ["S UW1 P"],
  "spider": ["S P AY1 D ER0"],
  "sponge": ["S P AH1 N JH"],
  "spoon": ["S P UW1 N"],
  "squid": ["S K W IH1 D"],
  "squirrel": ["S K W ER1 AH0 L"],
  "star": ["S T AA1 R"],
  "stop": ["S T AA1 P"],
  "storm": ["S T AO1 R M"],
  "strawberry": ["S T R AO1 B EH2 R IY0"],
  "strong": ["S T R AO1 NG"],
  "subway": ["S AH1 B W EY2"],
  "sun": ["S AH1 N"],
  "sunflower": ["S AH1 N F L AW2 ER0"],
  "surf": ["S ER1 F"],
  "sushi": ["S UW1 SH IY0"],
  "swan": ["S W AA1 N", "S W AO1 N"],
  "swim": ["S W IH1 M"],
  "taco": ["T AA1 K OW0"],
  "talk": ["T AO1 K"],
  "taxi": ["T AE1 K S IY0"],
  "tea": ["T IY1"],
  "teacher": ["T IY1 CH ER0"],
  "teddy": ["T EH1 D IY0"],
  "telescope": ["T EH1 L AH0 S K OW2 P"],
  "ten": ["T EH1 N"],
  "tennis": ["T EH1 N AH0 S", "T EH1 N IH0 S"],
  "tent": ["T EH1 N T"],
  "that": ["DH AE1 T", "DH AH0 T"],
  "the": ["DH AH0", "DH AH1", "DH IY0"],
  "they": ["DH EY1"],
  "think": ["TH IH1 NG K"],
  "third": ["TH ER1 D"],
  "this": ["DH IH1 S", "DH IH0 S"],
  "thread": ["TH R EH1 D"],
  "three": ["TH R IY1"],
  "ticket": ["T IH1 K AH0 T", "T IH1 K IH0 T"],
  "tie": ["T AY1"],
  "tiger": ["T AY1 G ER0"],
  "to": ["T UW1", "T IH0", "T AH0"],
  "toilet": ["T OY1 L AH0 T"],
  "tomato": ["T AH0 M EY1 T OW2", "T AH0 M AA1 T OW2"],
  "tongue": ["T AH1 NG"],
  "tooth": ["T UW1 TH"],
  "tractor": ["T R AE1 K T ER0"],
  "train": ["T R EY1 N"],
  "trash": ["T R AE1 SH"],
  "tree": ["T R IY1"],
  "trolley": ["T R AA1 L IY0"],
  "trophy": ["T R OW1 F IY0"],
  "truck": ["T R AH1 K"],
  "trumpet": ["T R AH1 M P AH0 T"],
  "tub": ["T AH1 B"],
  "tulip": ["T UW1 L AH0 P"],
  "turkey": ["T ER1 K IY0"],
  "turtle": ["T ER1 T AH0 L"],
  "two": ["T UW1"],
  "umbrella": ["AH0 M B R EH1 L AH0", "AH1 M B R EH2 L AH0"],
  "unicorn": ["Y UW1 N IH0 K AO2 R N"],
  "up": ["AH1 P"],
  "us": ["AH1 S", "Y UW2 EH1 S"],
  "van": ["V AE1 N"],
  "vest": ["V EH1 S T"],
  "violin": ["V AY0 AH0 L IH1 N"],
  "volcano": ["V AA0 L K EY1 N OW0"],
  "waffle": ["W AA1 F AH0 L"],
  "walk": ["W AO1 K", "W AA1 K"],
  "wall": ["W AO1 L"],
  "was": ["W AA1 Z", "W AH0 Z"],
  "watch": ["W AA1 CH", "W AO1 CH"],
  "water": ["W AO1 T ER0"],
  "wave": ["W EY1 V"],
  "we": ["W IY1"],
  "web": ["W EH1 B"],
  "whale": ["W EY1 L", "HH W EY1 L"],
  "white": ["W AY1 T", "HH W AY1 T"],
  "wind": ["W AY1 N D", "W IH1 N D"],
  "window": ["W IH1 N D OW0"],
  "wink": ["W IH1 NG K"],
  "with": ["W IH1 DH", "W IH1 TH", "W IH0 TH", "W IH0 DH"],
  "wizard": ["W IH1 Z ER0 D"],
  "wolf": ["W UH1 L F"],
  "worm": ["W ER1 M"],
  "wrench": ["R EH1 N CH"],
  "write": ["R AY1 T"],
  "yarn": ["Y AA1 R N"],
  "yellow": ["Y EH1 L OW0"],
  "you": ["Y UW1"],
  "yoyo": ["Y OW1 Y OW0"],
  "zebra": ["Z IY1 B R AH0"],
  "zero": ["Z IH1 R OW0", "Z IY1 R OW0"],
};
